### ISSUE TITLE
Tendermint stops building blocks

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1754]
**BUG REPORT**

**Tendermint version** 
0.20.0-27bd1dea

**ABCI app**
Custom closed Source. Based on jABCI (https://github.com/jTendermint/jabci)

**Environment**:
- OSX
- Binary release package
- 4 nodes, 3 validators, all running localhost
- UPDATE: 1 Validator is entered as seed/persistent peer in all other nodes.
- create_empty_blocks == false

**What happened**:
After several blocks, tendermint no longer creates new blocks on new transactions.
CheckTx runs successful and a `added good tx` message is found in the logs but nothing else happens.
There are several tx types. Most tx are around 10kb in size.
The tx that is tried to be sent is ~280bytes
Also, tendermint reports several older tx to be as duplicate in the mempool, no idea where that is coming from.

Please see the following dump consensus output of the validator node,  to which the tx is sent:

```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "round_state": {
      "height": 187,
      "round": 0,
      "step": 4,
      "start_time": "2018-06-15T17:11:48.984420411+02:00",
      "commit_time": "0001-01-01T00:00:00Z",
      "validators": {
        "validators": [
          {
            "address": "377218B1A5419768569B7829CE95C774F125DB35",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "8xEJkW3ghtHrLg0JBXvRi4xzUEy4KkuqMGtgODlkE/U="
            },
            "voting_power": 10,
            "accum": -20
          },
          {
            "address": "7F529D2F03B68924E5BB5F880C828CF8D134B8BD",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "eRmCyNdnKbsJWyFkSxLWcyduXKKdu/ZG2eue3ud3dA0="
            },
            "voting_power": 10,
            "accum": 10
          },
          {
            "address": "B5A8E53B84C94FB98C94C487FC19B0CC4F490DEA",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "xZYfYQGfrDi4dFF1ETY6qRGFfyZ6HUg7OpdRJpS1BAY="
            },
            "voting_power": 10,
            "accum": 10
          }
        ],
        "proposer": {
          "address": "377218B1A5419768569B7829CE95C774F125DB35",
          "pub_key": {
            "type": "AC26791624DE60",
            "value": "8xEJkW3ghtHrLg0JBXvRi4xzUEy4KkuqMGtgODlkE/U="
          },
          "voting_power": 10,
          "accum": -20
        }
      },
      "proposal": null,
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": 0,
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": 0,
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": 0,
          "prevotes": [
            "nil-Vote",
            "nil-Vote",
            "Vote{2:B5A8E53B84C9 187/00/1(Prevote) 000000000000 /10109156264A.../ @ 2018-06-15T13:03:28.555Z}"
          ],
          "prevotes_bit_array": "BA{3:__x} 10/30 = 0.33",
          "precommits": [
            "nil-Vote",
            "nil-Vote",
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{3:___} 0/30 = 0.00"
        }
      ],
      "commit_round": -1,
      "last_commit": {
        "votes": [
          "Vote{0:377218B1A541 186/00/2(Precommit) D59853BA0199 /4A91804010D3.../ @ 2018-06-15T13:03:25.447Z}",
          "Vote{1:7F529D2F03B6 186/00/2(Precommit) D59853BA0199 /E922055E2CE0.../ @ 2018-06-15T13:03:25.447Z}",
          "Vote{2:B5A8E53B84C9 186/00/2(Precommit) D59853BA0199 /E625746B6EBA.../ @ 2018-06-15T13:03:25.349Z}"
        ],
        "votes_bit_array": "BA{3:xxx} 30/30 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "377218B1A5419768569B7829CE95C774F125DB35",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "8xEJkW3ghtHrLg0JBXvRi4xzUEy4KkuqMGtgODlkE/U="
            },
            "voting_power": 10,
            "accum": 0
          },
          {
            "address": "7F529D2F03B68924E5BB5F880C828CF8D134B8BD",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "eRmCyNdnKbsJWyFkSxLWcyduXKKdu/ZG2eue3ud3dA0="
            },
            "voting_power": 10,
            "accum": 0
          },
          {
            "address": "B5A8E53B84C94FB98C94C487FC19B0CC4F490DEA",
            "pub_key": {
              "type": "AC26791624DE60",
              "value": "xZYfYQGfrDi4dFF1ETY6qRGFfyZ6HUg7OpdRJpS1BAY="
            },
            "voting_power": 10,
            "accum": 0
          }
        ],
        "proposer": {
          "address": "B5A8E53B84C94FB98C94C487FC19B0CC4F490DEA",
          "pub_key": {
            "type": "AC26791624DE60",
            "value": "xZYfYQGfrDi4dFF1ETY6qRGFfyZ6HUg7OpdRJpS1BAY="
          },
          "voting_power": 10,
          "accum": 0
        }
      }
    },
    "peers": [
      {
        "node_address": "b7ea63cf5733de753713fbf310bdbc208be75db9@192.168.55.1:46676",
        "peer_state": {
          "round_state": {
            "height": 187,
            "round": 0,
            "step": 2,
            "start_time": "2018-06-15T15:03:27.114897224+02:00",
            "proposal": false,
            "proposal_block_parts_header": {
              "total": 0,
              "hash": ""
            },
            "proposal_block_parts": null,
            "proposal_pol_round": -1,
            "proposal_pol": "___",
            "prevotes": "__x",
            "precommits": "___",
            "last_commit_round": 0,
            "last_commit": null,
            "catchup_commit_round": -1,
            "catchup_commit": "___"
          },
          "stats": {
            "last_vote_height": 0,
            "votes": 0,
            "last_block_part_height": 0,
            "block_parts": 0
          }
        }
      },
      {
        "node_address": "852b63f18af14884768aac6837b3643a6b3a9241@192.168.55.1:46666",
        "peer_state": {
          "round_state": {
            "height": 187,
            "round": 0,
            "step": 2,
            "start_time": "2018-06-15T15:03:27.118553416+02:00",
            "proposal": false,
            "proposal_block_parts_header": {
              "total": 0,
              "hash": ""
            },
            "proposal_block_parts": null,
            "proposal_pol_round": -1,
            "proposal_pol": "___",
            "prevotes": "__x",
            "precommits": "___",
            "last_commit_round": 0,
            "last_commit": null,
            "catchup_commit_round": -1,
            "catchup_commit": "___"
          },
          "stats": {
            "last_vote_height": 0,
            "votes": 0,
            "last_block_part_height": 0,
            "block_parts": 0
          }
        }
      },
      {
        "node_address": "83bfefedfe49668513e2067dbd6c6d2d158ba0a8@192.168.55.1:46686",
        "peer_state": {
          "round_state": {
            "height": 187,
            "round": 0,
            "step": 2,
            "start_time": "2018-06-15T15:03:26.784035233+02:00",
            "proposal": false,
            "proposal_block_parts_header": {
              "total": 0,
              "hash": ""
            },
            "proposal_block_parts": null,
            "proposal_pol_round": -1,
            "proposal_pol": "___",
            "prevotes": "__x",
            "precommits": "___",
            "last_commit_round": 0,
            "last_commit": "___",
            "catchup_commit_round": -1,
            "catchup_commit": "___"
          },
          "stats": {
            "last_vote_height": 187,
            "votes": 1,
            "last_block_part_height": 0,
            "block_parts": 0
          }
        }
      }
    ]
  }
}
```

**What you expected to happen**:
Block should be built on new tx

**Anything else do we need to know**:
Using `max_block_size_txs = 100` due to the fact that the default 10k leads to problems with hardcoded blocksize limit in load test scenarios (when we really pump tx)

**Comment by srmo** [comment]
Here's the SIGABRT output after sending sigabrt to the node after sending a tx that was accepted as good no no block is built. The noe is a validator node and the only seed for the other 3 nodes.
https://gist.github.com/srmo/d6419749e69f454ee450c3af992efe4a

**Comment by ebuchman** [comment]
Hmm - do you have logs to go with this too ?

**Comment by srmo** [comment]
Sure, also, after resetarting everything the same behavior is observed, although now the `duplicate tx messages` are gone, probably because in-memory mempool is empty?

*Node 1* (the one receiving the transaction via broadcast_tx_sync)
```
I[06-15|18:48:02.918] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:02.918] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:48:03.050] Added good transaction                       module=mempool tx=B0009C010E22CE2D9B385882C9F91C8D5BB6ACC1 res="&{CheckTx:fee:<> }"
I[06-15|18:48:03.050] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=broadcast_tx_sync
I[06-15|18:48:03.406] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=3 numDialing=0 numToDial=10
I[06-15|18:48:03.406] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:54830} b7ea63cf5733de753713fbf310bdbc208be75db9 in}"
I[06-15|18:48:12.921] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:12.922] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:48:22.928] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:22.928] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:48:32.935] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:32.935] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:48:33.405] Saving AddrBook to file                      module=p2p book=0/config/addrbook.json size=0
I[06-15|18:48:33.405] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=3 numDialing=0 numToDial=10
I[06-15|18:48:33.407] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:54851} 83bfefedfe49668513e2067dbd6c6d2d158ba0a8 in}"
I[06-15|18:48:42.942] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:42.942] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:48:52.949] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:48:52.950] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:49:02.955] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=status
I[06-15|18:49:02.956] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54743 method=dump_consensus_state
I[06-15|18:49:03.404] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=3 numDialing=0 numToDial=10
```

*Node 2*
```
I[06-15|18:48:00.446] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:00.446] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:09.353] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:09.354] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:48:19.360] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:19.360] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:48:29.365] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:29.366] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:48:30.445] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:30.445] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:39.370] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:39.371] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:48:49.376] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:49.377] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:48:59.382] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=status
I[06-15|18:48:59.383] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54788 method=dump_consensus_state
I[06-15|18:49:00.443] Saving AddrBook to file                      module=p2p book=1/config/addrbook.json size=0
I[06-15|18:49:00.444] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:49:00.444] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
```

*Node 3*
```
I[06-15|18:48:04.543] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:04.544] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:48:06.495] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:06.495] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:14.547] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:14.547] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:48:24.555] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:24.556] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:48:34.561] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:34.562] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:48:36.494] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:36.494] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:44.567] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:44.568] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:48:54.572] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:48:54.572] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:49:04.577] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=status
I[06-15|18:49:04.577] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54831 method=dump_consensus_state
I[06-15|18:49:06.493] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:49:06.493] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
```

*Node 4*
```
I[06-15|18:48:00.337] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:00.338] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:48:00.531] Saving AddrBook to file                      module=p2p book=3/config/addrbook.json size=0
I[06-15|18:48:00.533] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:00.533] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:10.343] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:10.343] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:48:20.350] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:20.350] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:48:30.357] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:30.357] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:48:30.532] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:48:30.532] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
I[06-15|18:48:40.362] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:40.363] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:48:50.371] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:48:50.372] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:49:00.378] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=status
I[06-15|18:49:00.378] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:54853 method=dump_consensus_state
I[06-15|18:49:00.531] Ensure peers                                 module=p2p numOutPeers=1 numInPeers=0 numDialing=0 numToDial=9
I[06-15|18:49:00.531] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{127.0.0.1:46656} 14a6dcadc896a08e87ea12ff464711d889d5b77a out}"
```

**Comment by ebuchman** [comment]
Thanks for the extra details. Is this replicable, or have you only seen it once ?

**Comment by srmo** [comment]
@ebuchman I can reproduce it.
see the following gists:

- node1
-- here's where I start sending transactions (manually)
-- https://gist.github.com/srmo/26d3ba9346cf52096232eb1023594bad

- node2
-- when this node sees a certain tx sent by 1, it will start itself sending transactions
-- https://gist.github.com/srmo/ed165b4930c3ddf6c2d81dd4f9d0bc4b

- node 3
-- just an observer
-- https://gist.github.com/srmo/980d0c08c9c485d8e6b9fb6f79961388

- node 4
-- just an observer
-- https://gist.github.com/srmo/cebf085dba9f7342d1d07a9bb87c3351

So it seems as if this happens when node 2 also starts sending tx concurrently with node 1.
Not really sure so it might be a misleading trail.

**Comment by srmo** [comment]
Strange to me are the "duplicate tx in cache" messages, I will double check but it's 99.9999..% certain that each tx broadcast differes at least in one field (using generated UUIDs for message ids) though this is something I will investigate further.

**Comment by srmo** [comment]
We had a quick discussion about the Gists. One thing that comes to mind is that the "Could not checkTx - duplicate transaction" messages are not supposed to happen.
Our application is guaranteed to generate uniqe transactions.
That means, that the node was not able to identify a transaction as a tx he was originally broadcasting and is just receiving it back from some other node.
Could this be a problem?

**Comment by srmo** [comment]
Just figured that node 1 7F529D2F03B68924E5BB5F880C828CF8D134B8BD was supposed to be proposer for the empty block @height 56 but they never come to vote on it. We are unable to figure out what node 1 is doing at this height.

I'll restart with debug output, as restarting the whole thing also does not progress to height 56 but stys stuck on 55

No idea what's going on. Race in ABCI connection? Some deadlock somewhere? We have a hard time consistently reproducing it, but it is reproducible, from time to time :/

**Comment by ebuchman** [comment]
Thanks for the reports. We'll get this sorted

**Comment by ebuchman** [comment]
I'm able to replicate this pretty easily with the `make localnet-start` command and sending a transaction to one of the nodes. Not every time, but certainly a replicable issue.

It seems the issue might actually be with the mempool reactor not gossiping the tx - I find if I also send the tx to all the other nodes, I get a block.

**Comment by ebuchman** [comment]
Ok, I think I figured it out. See PR #1764

**Comment by ebuchman** [comment]
Any chance you can test and confirm it fixes the issue ? Seems to work when I run it with the `make localnet-start` locally now, but hard to write a unit test for (noted in #1559)

**Comment by ebuchman** [comment]
> PS: please be aware that the whole setup (computer) has been in hibernate for apr. 1hour before sending a new tx and sending the sigabrt.

Does this mean the nodes were down and they were restarted before sending the tx ?

The fix I pushed will only fix this issue if it happens right after a rest and we switch from fast sync to consensus. But if its happening spontaneously in normal operation, the issue might exist elsewhere too (could be same cause).

**Comment by srmo** [comment]
@ebuchman thanks for the quick patch!
So far I was not able to reproduce the behavior. I'm going to crank up the load and have an additional test run in our test environment. I'm still concerned with https://github.com/tendermint/tendermint/issues/1762 still being able to reproduce the issue. Will have a look over there if this holds true.

Re:
>> PS: please be aware that the whole setup (computer) has been in hibernate for apr. 1hour before sending a new tx and sending the sigabrt.
> Does this mean the nodes were down and they were restarted before sending the tx ?

The nodes were up all the time when the behavior was observed. I kept them running (without sending TXs) when I closed the laptop to drive home :)
After that, I just spun up the machine again and retried sending a tx.

I saw this issue happen sontaneously in normal operation.

I'll keep posted here when I was able to run a bit mor loady tests.

Question: I saw mentioned that the default params for send/recv rate and packet size will be increased. I'm still running everything with the old default params. Is that a problem?

**Comment by srmo** [comment]
@ebuchman the problem still happens in a low-load scenario. I.e. the nodes stop building blocks.
should I continue discussion in https://github.com/tendermint/tendermint/issues/1762 ?

Side note: the txs are shown in the "unconfirmed_tx" endpoint. And when I restart one of the other nodes, the transactions are actually built into new blocks.

**Comment by srmo** [comment]
PS: all 4 nodes are configured as validator in the current scenario

**Comment by xla** [comment]
@srmo Thanks for the extra info, we actively working to resolve this issue. Let’s consolidate in #1762
