### ISSUE TITLE
Confusing links in ABCI Readme

### ISSUE THREAD

**Issue by nick-morhun** [tendermint/tendermint#2335]
Hi,
it seems like there are obsolete links at [https://github.com/tendermint/tendermint/tree/master/abci#specification](https://github.com/tendermint/tendermint/tree/master/abci#specification)

They lead to the old repo.

**Comment by zramsay** [comment]
fixed ^

**Comment by iamcap7** [comment]
Hi, the link to the prose specification

https://github.com/tendermint/tendermint/blob/master/abci/specification.md

is still broken.

**Comment by zramsay** [comment]
https://tendermint.com/docs/spec/abci/abci.html#overview

and
https://github.com/tendermint/tendermint/tree/master/docs/spec/abci

**Comment by iamcap7** [comment]
Ah, thanks! That's great.

Also, I was just trying to point out that in the readme

https://github.com/tendermint/tendermint/blob/master/abci/README.md

the actual link "[A prose specification](...)" is broken. I wasn't sure where it should be directed otherwise I would have made a PR.

**Comment by zramsay** [comment]
@iamcap7 thanks for pointing where you found that broken link - turns out I have an old branch that fixes these links and better organizes the ABCI content, stay tuned!
