### ISSUE TITLE
Single node integration test, regularly can't include transactions in a block

### ISSUE THREAD

**Issue by mattkanwisher** [tendermint/tendermint#3057]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.27.3 Note with increased broadcastTxCommit timeout to 2 minutes
https://github.com/mattkanwisher/tendermint/commit/9a8cb94fad835aeb4b8507f8ab34d59cb75f3926

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Loom SDK 

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Install tools**:
- **Others**:

**What happened**:
We have an integration test suite for one of our games, that runs in both 1 node and 4 node configurations. Recent builds of tendermint, the 1 node clusters almost always fail once intermittently, whereas the 4 node clusters never fail on broadcast_tx_commit. These 4 nodes are running on a single piece of hardware for an integration test, same with the 1 node, same CI server even. 

Err we get is 
"Timed out waiting for tx to be included in a block"

**What you expected to happen**:

Wouldn't expect broadcast_tx_commit  to ever timeout in a single node configuration with the client and server on same hardware.

**Have you tried the latest version**: yes/no yes 

**How to reproduce it** (as minimally and precisely as possible):

Sadly only can do this with our integration suite, but it is super easy for us to run this with different versions of tendermint, if we think there is a fix.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

[single_node_consensus_fail_integration_test.log](https://github.com/tendermint/tendermint/files/2700343/single_node_consensus_fail_integration_test.log)

**Config (you can paste only the changes you've made)**:

```
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"
```

We have tried tweaking these numbers in a number of ways, there is no particular reason why we ended up here except its half of what you recommend for production systems.

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by ebuchman** [comment]
Could this explain it:

```
I[19126-12-19|07:10:53.646] Recheck txs                                  module=mempool numtxs=1 height=19
E[19126-12-19|07:10:53.647] CheckTx: sequence number does not match expected 5 got 4 module=loom 
I[19126-12-19|07:10:53.647] Tx is no longer valid                        module=mempool tx=2D4CC7D26B8BEA19B7290C98ADD5239AC4D6044E8F6792A92356DB5FE7A61DB3 res="&{CheckTx:code:1 log:\"sequence number does not match expected 5 got 4\" }" err=null
```

`broadcast_tx_commit` is not smart enough to return an error if the tx passes CheckTx but later fails during a recheck, so it would just hang until the timeout.

**Comment by mattkanwisher** [comment]
Hrmm is the abci layer aware of a recheck? So what happens if I get a checkTx twice for the same transaction? How is the app layer supposed to do stateful nonce tracking during checkTxs inside a single block

**Comment by ebuchman** [comment]
The CheckTx state should be reset with every abci.Commit. Then the recheck will call CheckTx for all txs left in the mempool on top of that fresh state, which should be identical to that of the latest block, and thus as if the txs being rechecked were only being received in the mempool for the first time. Does that make sense?

See https://tendermint.com/docs/spec/abci/apps.html#state

**Comment by ebuchman** [comment]
@mattkanwisher was the above helpful in resolving this?

**Comment by ebuchman** [comment]
Closing this - let us know if there's still an issue.

**Comment by hikingpig** [comment]
Hi, does upgrade tendermint to lastest version 0.37.3 solved the issue?

**Comment by ebuchman** [comment]
Solved in what sense ? The issue may have been a misunderstanding of how certain rpc calls work. Please open a new issue with complete details if you're having some problem.

**Comment by hikingpig** [comment]
After I got this timeout response, the transaction is still included in the block later. How later is not fixed. Sometimes immediately, sometimes several seconds later. Can we be sure that the transaction will be included in this case if the network functions normally? How can we get confirmation from the network?

**Comment by ebuchman** [comment]
You can't guarantee it, but we make a best effort. To guarantee you need to either poll a tx endpoint to search for the tx or subscribe to a tx event to see that it was committed. The timeout just means the tx didn't get committed within some small amount of time, but it doesn't mean it won't be committed later (usually it will, unless all nodes that have seen it crash or something weird happens)
