### ISSUE TITLE
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by jjhesk** [tendermint/tendermint#5084]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.33.6

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
built-in
**Environment**:
- **OS** (e.g. from /etc/os-release): darwin
- **Install tools**:
- **Others**:

**What happened**:
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**What you expected to happen**:
I[2020-07-04|04:23:18.354] starting ABCI with Tendermint module=main
I[2020-07-04|04:23:18.361] Starting application REST service (chain-id: "darkpool-1x")... module=rest-server
I[2020-07-04|04:23:18.361] Starting RPC HTTP server on 127.0.0.1:1317 module=rest-server
project ProjectDocs
project params
payment PaymentTemplates
payment PaymentContracts
payment Subscriptions
BondDocs ===
Bonds ===
Batches ===
Oracles
Oracles ok!
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):
start a fresh development kit with sdk 0.38.5 from https://github.com/tokenchain/dp-hub/tree/1.3.8x

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
the result has ERROR: ABCIQuery: Post failed: Post "http://localhost:26657": dial tcp [::1]:26657: connect: connection refused
when try to add staking validator with demon it stopped and refused the connection.
**Config (you can paste only the changes you've made)**:

```
yes $PASSWORD | $DEMON gentx \
  --amount 10000$TOKEN_SYM \
  --pubkey $($DEMON tendermint show-validator) \
  --name stardust \
  --commission-rate "0.10" \
  --commission-max-rate "0.10" \
  --commission-max-change-rate "0.10"

echo "====================================="
echo "add a validator"
echo "====================================="
yes $PASSWORD | $DCLI tx staking create-validator \
  --amount=10000000$TOKEN_SYM \
  --pubkey=$($DEMON tendermint show-validator) \
  --moniker=$MONIKER \
  --chain-id=$CHAIN_ID \
  --commission-rate="0.10" \
  --commission-max-rate="0.20" \
  --commission-max-change-rate="0.01" \
  --min-self-delegation="1" \
  --gas="auto" \
  --gas-prices="0.025$TOKEN_SYM" \
  --from=apple
```

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
Based on the excerpt above you are not collecting gentxs. You must do this prior to starting the chain otherwise your validator set will be empty. If you follow the sdk tutorials at tutorials.cosmos.network you will find these instructions

**Comment by jjhesk** [comment]
@marbar3778 from the gentxs above I was able to collect all the txs
```json
collect-gentxs
=====================================
{"app_message":{"auth":{"accounts":[{"type":"cosmos-sdk/Account","value":{"account_number":0,"address":"dx01f4a5keuhdrvydltht4g3krvjuv2ejp5v654mwf","coins":[{"amount":"10000000000","denom":"dap"},{"amount":"10000000","denom":"dollar"},{"amount":"100000000","denom":"stake"}],"public_key":"","sequence":0}},{"type":"cosmos-sdk/Account","value":{"account_number":0,"address":"dx01hk0h45g77knq0l2cllrj0adjmfv7nynzm9nwrl","coins":[{"amount":"100","denom":"dap"},{"amount":"10000","denom":"dollar"},{"amount":"100000000","denom":"stake"}],"public_key":"","sequence":0}},{"type":"cosmos-sdk/Account","value":{"account_number":0,"address":"dx01vxn4yh85cttuxg9yryzmvmn9y9gscfjr6w7xw8","coins":[{"amount":"100","denom":"dap"},{"amount":"10000","denom":"dollar"},{"amount":"100000000","denom":"stake"}],"public_key":"","sequence":0}},{"type":"cosmos-sdk/Account","value":{"account_number":0,"address":"dx01w732rlhkdzz099cvvss977rfhvjn0r5r3w6rqd","coins":[{"amount":"10000000","denom":"dap"},{"amount":"10000","denom":"dollar"},{"amount":"100000000","denom":"stake"}],"public_key":"","sequence":0}}],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"bank":{"send_enabled":true},"bonddoc":{"bond_docs":null},"bonds":{"batches":null,"bonds":null},"crisis":{"constant_fee":{"amount":"1000","denom":"dap"}},"did":{"did_docs":null},"distribution":{"delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.010000000000000000","bonus_proposer_reward":"0.040000000000000000","community_tax":"0.020000000000000000","withdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"evidence":{"evidence":[],"params":{"max_evidence_age":"120000000000"}},"genutil":{"gentxs":[{"type":"cosmos-sdk/StdTx","value":{"fee":{"amount":[],"gas":"200000"},"memo":"91f20d2af33139c38a3c4eaf84141ea76f5a9956@192.168.1.2:26656","msg":[{"type":"cosmos-sdk/MsgCreateValidator","value":{"commission":{"max_change_rate":"0.100000000000000000","max_rate":"0.100000000000000000","rate":"0.100000000000000000"},"delegator_address":"dx01f4a5keuhdrvydltht4g3krvjuv2ejp5v654mwf","description":{"details":"","identity":"","moniker":"dphomeworld","security_contact":"","website":""},"min_self_delegation":"1","pubkey":"dx0valconspub1zcjduepqqajyah2ev496nwn3ge6njgamqf2gqfjpahs5perelwvt05l83jusuplx9y","validator_address":"dx0valoper1f4a5keuhdrvydltht4g3krvjuv2ejp5vkj0stf","value":{"amount":"10500","denom":"dap"}}}],"signatures":[{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"AznEjD5hOQ8myGJrWcEuMqvy52fDnI8sqDpqleg0eGK5"},"signature":"XSwYOIuWliGjMd/lJdo6gtAQ2g1s0hpRtnLT6QpCoyoBZBLwnXUq0tjgKyVWdw5dDbncTzQK8pGRKDbIlczeUA=="}]}}]},"gov":{"deposit_params":{"max_deposit_period":"172800000000000","min_deposit":[{"amount":"10000000","denom":"stake"}]},"deposits":null,"proposals":null,"starting_proposal_id":"1","tally_params":{"quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto":"0.334000000000000000"},"votes":null,"voting_params":{"voting_period":"172800000000000"}},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.130000000000000000"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"stake"}},"nameservice":{"whois_records":[]},"oracles":{"oracles":[{"capabilities":[{"capabilities":["mint"],"denom":"dap"}],"oracle_did":"did:dxp:XX1rB7o9BeEmNuvB5PeAn2"},{"capabilities":[{"capabilities":["mint","burn","transfer"],"denom":"dap"}],"oracle_did":"did:dxp:Xc7PR8S7A6AzreYR5th2h4"},{"capabilities":[{"capabilities":["transfer"],"denom":"dollar"},{"capabilities":["transfer"],"denom":"dap"}],"oracle_did":"did:dxp:QmuNtGJCJZuU8wm8e9PSWk"},{"capabilities":[{"capabilities":["transfer","burn","mint"],"denom":"dollar"}],"oracle_did":"did:dxp:PQQMd4iP8XUpctiETKRhW2"}]},"params":null,"payments":{"params":{"claim_fee_amount":"600.000000000000000000","evaluation_agent_registration_fee_amount":"0.000000000000000000","evaluation_fee_amount":"400.000000000000000000","evaluation_pay_fee_percentage":"0.100000000000000000","evaluation_pay_node_fee_percentage":"0.400000000000000000","initiation_fee_amount":"500000.000000000000000000","initiation_node_fee_percentage":"0.000000000000000000","ixo_factor":"1.000000000000000000","node_fee_percentage":"0.500000000000000000","service_agent_registration_fee_amount":"0.000000000000000000"},"payment_contracts":null,"payment_templates":null,"subscriptions":null},"project":{"account_maps":null,"params":{"dp_did":"did:dxp:PGtRP4o5cCYhe8B5Fu7xj6","project_minimum_initial_funding":"1"},"project_docs":null,"withdrawal_infos":null},"slashing":{"missed_blocks":{},"params":{"downtime_jail_duration":"600000000000","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":{}},"staking":{"delegations":null,"exported":false,"last_total_power":"0","last_validator_powers":null,"params":{"bond_denom":"dap","historical_entries":0,"max_entries":7,"max_validators":100,"unbonding_time":"1814400000000000"},"redelegations":null,"unbonding_delegations":null,"validators":null},"supply":{"supply":[]},"treasury":null,"upgrade":{}},"chain_id":"darkpool-1x","gentxs_dir":"/Users/hesk/.dpd/config/gentx","moniker":"dphomeworld","node_id":"91f20d2af33139c38a3c4eaf84141ea76f5a9956"}
```

**Comment by jjhesk** [comment]
@marbar3778 
I have tried both
```
[rpc]
laddr="http://locahost:26657"
```

and 
```
[rpc]
laddr="tcp://0.0.0.0:26657"
```

**Comment by jjhesk** [comment]
ok, it is resolved by the amount of gentx. https://github.com/cosmos/scaffold/issues/57

**Comment by marbar3778** [comment]
perfekt!! I am not sure how that was giving you a connection refused error but happy it is fixed

**Comment by jjhesk** [comment]
It is confirmed that if the staking amount is not enough then gentx will not generate the validator and it will lead to this error.

**Comment by perfogic** [comment]
Hello, I'm puting 900000000stake over 100000000stake (90%) but I still face this error LOL. Can you help ? @jjhesk
